---
name: 'Buildroot SBOM generator'
description: 'Generates buildroot SBOM and legal-info and publishes them as artifacts'

inputs:
  output-directory: # Location of buildroot output directory
    description: 'Buildroot output dir'
    required: true
    default: './output'

  repo-version: # Version of the repository
    description: 'Version of the repository'
    required: true
    default: '0.0.0'

  repo-name: # Name of the repository
    description: 'Name of the repository'
    required: true
    default: 'my-repo'

  repo-owner: # Owner of the repository
    description: 'Owner of the repository'
    required: true
    default: 'my-org'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Generate legal-info
      run: |
        pushd ${{ inputs.output-directory }}
        make legal-info
        make show-info > legal-info/cpe.json
        popd

    - name: Generate SBOM
      env:
        CYCLONE_DX_SCRIPT: "~/.local/lib/python3.10/site-packages/src/CycloneDX-Buildroot/generateBuildrootSBOM.py"
      run: |
        pip3 install CycloneDX-Buildroot
        pushd ${{ inputs.output-directory }}/legal-info
        python $(CYCLONE_DX_SCRIPT) -i manifest.csv -c cpe.json -o sbom -n ${{ inputs.repo-name }} -v ${{ inputs.repo-version }} -m ${{ inputs.repo-owner }}
        popd

    - name: Tar legal-info
      run: |
        pushd  ${{ inputs.output-directory }}
        tar -czf legal-info.tar.gz legal-info
        popd

    - name: Publish legal-info
      uses: actions/upload-artifact@v4
      with:
        name: legal-info-${{ inputs.repo-version }}.tar.gz
        path: ./output/legal-info.tar.gz

