---
name: 'Buildroot SBOM generator'
description: 'Generates buildroot SBOM and legal-info and publishes them as artifacts'

inputs:
  output-directory: # Location of buildroot output directory
    description: 'Buildroot output dir'
    required: true
    default: './output'

  repo-version: # Version of the repository
    description: 'Version of the repository'
    required: true
    default: '0.0.0'

  repo-name: # Name of the repository
    description: 'Name of the repository'
    required: true
    default: 'my-repo'

  repo-owner: # Owner of the repository
    description: 'Owner of the repository'
    required: true
    default: 'my-org'

  publish-legal-info: # Publish legal-info - this can be very large
    description: 'Publish legal-info'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Generate legal-info
      shell: bash
      run: |
        pushd ${{ inputs.output-directory }}
        make legal-info
        make show-info > legal-info/cpe.json
        popd

    - name: Generate SBOM
      shell: bash
      env:
        CYCLONE_DX_SCRIPT: "./venv/lib/python3.10/site-packages/src/CycloneDX-Buildroot/generateBuildrootSBOM.py"
      run: |
        python3 -m venv venv
        source ./venv/bin/activate
        pip3 install CycloneDX-Buildroot
        pushd ${{ inputs.output-directory }}/legal-info
        python ${{ env.CYCLONE_DX_SCRIPT }} -i manifest.csv -c cpe.json -o sbom -n "${{ inputs.repo-name }}" -v "${{ inputs.repo-version }}" -m "${{ inputs.repo-owner }}"
        deactivate
        popd

    - name: Tar legal-info
      shell: bash
      run: |
        pushd  ${{ inputs.output-directory }}
        tar -czf legal-info.tar.gz legal-info
        popd

    - name: Publish SBOM json
      uses: actions/upload-artifact@v4
      with:
        name: sbom-${{ inputs.repo-version }}.json
        path: ./output/legal-info/sbom.json

    - name: Publish legal-info
      # This can be very large, so only publish if needed.
      if: ${{ inputs.publish-legal-info == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: legal-info-${{ inputs.repo-version }}.tar.gz
        path: ./output/legal-info.tar.gz

